### ISSUE TITLE
Support %FSD

### ISSUE THREAD

**Issue by kasbah** [mcous/gerber-parser#18]
Just came across this [in the kicad-dev mailing list](https://lists.launchpad.net/kicad-developers/msg31041.html) and thought I would make a note of it. 

> %FSD is used by older versions of Altium Designer [1], PADS, Allergro and CircuitCAM, among others, to denote that coordinate zeros should include _both_ leading a trailing zeros.  While this has never been part of the RS274 standard, it is understood by some manufacturers[2] and is parsed by other gerber viewers[3][4][5].

> [1]
> http://www.altium.com/documentation/sites/default/files/wiki_attachments/255441/Gerber%20Advanced%20AD.png
> [2] https://www.eurocircuits.com/rs274x-extended-gerber/
> [3] www.gerber-viewer.com/
> [4] https://circuitpeople.com/
> [5] http://gerbv.geda-project.org/
> [6]
> https://github.com/spqr/umichmoo/blob/master/schematics/moo1_1/altium-progheader/Gerbers/programmer.gbs
> [7]
> https://github.com/sonyxperiadev/CDB-Assist/blob/master/Hardware/CDBAssist-v3.1-OutlineRoute.gbr
> [8] http://zeus.pd.infn.it/MVD/download/pitch/pitch.ger

**Comment by mcous** [comment]
Not sure why I've let this issue sit here for so long; sorry about that. Closing because this repository isn't in use anymore and (more importantly) `gerber-parser` as it exists right now will handle FSD just fine by virtue of the fact that:

- The `%FS` block is allowed to have extra unknown characters
- If all zeros (and/or decimal points) are provided, coordinate parsing will work regardless of the zero-suppression setting
