### ISSUE TITLE
EasyEDA gerbers not supported

### ISSUE THREAD

**Issue by henrikekblad** [mcous/gerber-parser#19]
One of the users tried to upload gerbers generated from EasyEDA. 

The parser pukes and complains about the coordinate system. 
```
Error: cannot parse coordinate with format undefined
    at parse (/home/oh/openhardware/node_modules/gerber-parser/lib/parse-coord.js:23:11)
    at parse (/home/oh/openhardware/node_modules/gerber-parser/lib/_parse-gerber.js:236:19)
```

[in wall scene controller power supply brd.zip](https://github.com/mcous/gerber-parser/files/1584367/in.wall.scene.controller.power.supply.brd.zip)

**Comment by mcous** [comment]
Wow this is a frustrating bug. There's an extra space after the `*` in the `G04` comment line right before the `%FS` block.

```
G04 leading zeros omitted , absolute positions ,2 integer and 4 * 
%FSLAX24Y24*%
```

Since the parser strips newlines between blocks (stuff between `*`s and `*%`s), the parser is choking because it doesn't recognize `[space]%FSLAX24Y24` as the same thing as `%FSLAX24Y24`. Careless programming on my part; should be easy enough to fix

**Comment by henrikekblad** [comment]
Wow, you're fast :) 

Happy X-mas btw.

**Comment by mcous** [comment]
Thanks, you too! It's the only time of the year I have a little bit of free time ⌚️

**Comment by mcous** [comment]
Fix released as `v1.0.7`

**Comment by henrikekblad** [comment]
Thanks! 
Can I expect you rolling this into gerber-to-svg/pcb-stackup also?

**Comment by mcous** [comment]
It should show up in new installs of dependent tools thanks to the magic of semver. You may need to update lockfiles if you use them. If that's too much, though, ping me on gitter and I can probably find some time to push out some patch releases

**Comment by henrikekblad** [comment]
Worked like a charm.
